Port set-output to GITHUB_OUTPUT
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/ci/legacy/.github/workflows/operator_ci.yaml b/ci/legacy/.github/workflows/operator_ci.yaml
--- a/ci/legacy/.github/workflows/operator_ci.yaml
+++ b/ci/legacy/.github/workflows/operator_ci.yaml
@@ -332,11 +332,11 @@ jobs:
           OP_TEST_MODIFIED_CSVS: "${{ steps.op-traffic-light.outputs.op_test_modified_csvs }}"
           OP_TEST_MODIFIED_CSVS_OTHERS: "${{ steps.op-traffic-light.outputs.op_test_modified_others }}"
         run: |
-          echo "::set-output name=op_check_cosmetic::0"
+          echo "op_check_cosmetic=0" >> $GITHUB_OUTPUT
           [[ $OP_TEST_RECREATE -eq 1 ]] && { echo "Recreating operator. Exiting with '0' ..."; exit 0; } || true
           [[ $OP_TEST_ALLOW_SERIOUS_CHANGES -eq 1 ]] && { echo "Allowing serious changes. Exiting with '0' ..."; exit 0; } || true
-          [ -n "$OP_TEST_MODIFIED_CSVS" ] && echo "::set-output name=op_check_cosmetic::1" || true
-          [ -n "$OP_TEST_MODIFIED_CSVS_OTHERS" ] && { echo -e "Error:\n    Modifying exiting operator version !!!\n    Only cosmetic changes are allowed !!! Please ask maintainers to set `allow/serious-changes-to-existing` label.\n    Files that cannot be changed : '$OP_TEST_MODIFIED_CSVS_OTHERS'"; echo "::set-output name=op_check_cosmetic::2"; exit 20; } || true
+          [ -n "$OP_TEST_MODIFIED_CSVS" ] && echo "op_check_cosmetic=1"  >> $GITHUB_OUTPUT || true
+          [ -n "$OP_TEST_MODIFIED_CSVS_OTHERS" ] && { echo -e "Error:\n    Modifying exiting operator version !!!\n    Only cosmetic changes are allowed !!! Please ask maintainers to set `allow/serious-changes-to-existing` label.\n    Files that cannot be changed : '$OP_TEST_MODIFIED_CSVS_OTHERS'"; echo "op_check_cosmetic=2" >> $GITHUB_OUTPUT; exit 20; } || true
 
       - name: "Comment for cosmetics change error when csv is changed"
         if: failure() && steps.op-verify-modifications.outputs.op_check_cosmetic == '2'
