[ISV-3044] Migrate GH actions save outputs to a new format (#358)
* Port set-output to GITHUB_OUTPUT

Signed-off-by: Martin Vala <mavala@redhat.com>

* Fixed actions/github-script@v6

Signed-off-by: Martin Vala <mavala@redhat.com>

* github.rest.issues

Signed-off-by: Martin Vala <mavala@redhat.com>

* Test

Signed-off-by: Martin Vala <mavala@redhat.com>

---------

Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/ci/legacy/.github/workflows/operator_ci.yaml b/ci/legacy/.github/workflows/operator_ci.yaml
--- a/ci/legacy/.github/workflows/operator_ci.yaml
+++ b/ci/legacy/.github/workflows/operator_ci.yaml
@@ -12,25 +12,25 @@ jobs:
     steps:
       - name: Remove automerge-disabled when needed
         if: ${{ env.AUTOMERGE_ENABLED == '1' }}
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'automerge-disabled'
             })
       - name: Add automerge-disabled when needed
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: ${{ env.AUTOMERGE_ENABLED == '0' }}
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -43,12 +43,12 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: "Remove kubernetes-operator"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -56,12 +56,12 @@ jobs:
             })
 
       - name: "Remove openshift-operator"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -73,13 +73,13 @@ jobs:
           repo-token: "${{ secrets.GITHUB_TOKEN }}"
 
       - name: "Remove package-validated"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: (!contains(github.event.pull_request.labels.*.name, 'do-not-merge/hold'))
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -87,13 +87,13 @@ jobs:
             })
 
       - name: "Add Assignees"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: github.event.action == 'opened' || github.event.action == 'reopened'
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addAssignees({
+            github.rest.issues.addAssignees({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -108,7 +108,7 @@ jobs:
       #   with:
       #     project: 'https://github.com/operator-framework/community-operators/projects/1'
       # - name: "Request reviewer (test)"
-      #   uses: actions/github-script@v3
+      #   uses: actions/github-script@v6
       #   continue-on-error: true
       #   with:
       #     github-token: ${{secrets.GITHUB_TOKEN}}
@@ -149,7 +149,7 @@ jobs:
       #     allow-repeats: false
 
       - name: "Remove installation-validated"
-        uses: actions/github-script@v4
+        uses: actions/github-script@v6
         if: (github.event.action != 'unlabeled')
         continue-on-error: true
         with:
@@ -157,7 +157,7 @@ jobs:
           script: |
             const arr = ['installation-validated', 'installation-validated-4.6', 'installation-validated-4.7', 'installation-validated-4.8'];
             for (let label of arr) {
-              github.issues.removeLabel({
+              github.rest.issues.removeLabel({
                 issue_number: context.issue.number,
                 owner: context.repo.owner,
                 repo: context.repo.repo,
@@ -298,13 +298,13 @@ jobs:
 
 
       - name: Update title
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         continue-on-error: true
         if: always() && steps.op-traffic-light.outputs.op_test_pr_title != ''
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.update({
+            github.rest.issues.update({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -312,13 +312,13 @@ jobs:
             })
 
       - name: Handle new operator
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.op_test_is_new_operatror == '1'
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -332,11 +332,11 @@ jobs:
           OP_TEST_MODIFIED_CSVS: "${{ steps.op-traffic-light.outputs.op_test_modified_csvs }}"
           OP_TEST_MODIFIED_CSVS_OTHERS: "${{ steps.op-traffic-light.outputs.op_test_modified_others }}"
         run: |
-          echo "::set-output name=op_check_cosmetic::0"
+          echo "op_check_cosmetic=0" >> $GITHUB_OUTPUT
           [[ $OP_TEST_RECREATE -eq 1 ]] && { echo "Recreating operator. Exiting with '0' ..."; exit 0; } || true
           [[ $OP_TEST_ALLOW_SERIOUS_CHANGES -eq 1 ]] && { echo "Allowing serious changes. Exiting with '0' ..."; exit 0; } || true
-          [ -n "$OP_TEST_MODIFIED_CSVS" ] && echo "::set-output name=op_check_cosmetic::1" || true
-          [ -n "$OP_TEST_MODIFIED_CSVS_OTHERS" ] && { echo -e "Error:\n    Modifying exiting operator version !!!\n    Only cosmetic changes are allowed !!! Please ask maintainers to set `allow/serious-changes-to-existing` label.\n    Files that cannot be changed : '$OP_TEST_MODIFIED_CSVS_OTHERS'"; echo "::set-output name=op_check_cosmetic::2"; exit 20; } || true
+          [ -n "$OP_TEST_MODIFIED_CSVS" ] && echo "op_check_cosmetic=1"  >> $GITHUB_OUTPUT || true
+          [ -n "$OP_TEST_MODIFIED_CSVS_OTHERS" ] && { echo -e "Error:\n    Modifying exiting operator version !!!\n    Only cosmetic changes are allowed !!! Please ask maintainers to set `allow/serious-changes-to-existing` label.\n    Files that cannot be changed : '$OP_TEST_MODIFIED_CSVS_OTHERS'"; echo "op_check_cosmetic=2" >> $GITHUB_OUTPUT; exit 20; } || true
 
       - name: "Comment for cosmetics change error when csv is changed"
         if: failure() && steps.op-verify-modifications.outputs.op_check_cosmetic == '2'
@@ -390,48 +390,48 @@ jobs:
           allow-repeats: true
 
       - name: "Removing Operator recreate label when exists"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.op_test_set_label_operator_version_overwrite == '1' && contains(github.event.pull_request.labels.*.name, 'allow/operator-recreate')
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'allow/operator-recreate'
             })
       - name: "Setting Operator version overwrite label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.op_test_set_label_operator_version_overwrite == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               labels: [ 'allow/operator-version-overwrite' ]
             })
       - name: "Removing Operator version overwrite label when exists"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.op_test_set_label_operator_recreate == '1' && contains(github.event.pull_request.labels.*.name, 'allow/operator-version-overwrite')
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'allow/operator-version-overwrite'
             })
       - name: "Setting Operator recreate label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.op_test_set_label_operator_recreate == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -455,12 +455,12 @@ jobs:
       #     configuration-path: "${{steps.op-traffic-light.outputs.op_test_stream }}/${{ steps.op-traffic-light.outputs.op_test_name }}/ci.yaml"
 
       - name: "Setting authorized-changes label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: steps.op-traffic-light.outputs.op_test_authorized_changes == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -504,13 +504,13 @@ jobs:
     steps:
 
       - name: "Remove needs-ok-to-test"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: always()
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.removeLabel({
+            github.rest.issues.removeLabel({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -522,12 +522,12 @@ jobs:
           echo "needs.operator-ci.outputs.op_test_ci_yaml_only: ${{ needs.operator-ci.outputs.op_test_ci_yaml_only }}"
 
       - name: "Setting ok-to-test label"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: needs.operator-ci.outputs.op_test_stream == 'community-operators' && needs.operator-ci.outputs.op_test_ci_yaml_only != '1' && (!contains(github.event.pull_request.labels.*.name, 'allow/ci-changes'))
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
@@ -535,12 +535,12 @@ jobs:
             })
 
       - name: "Setting installation-validated label (opensift+ci_yaml_only)"
-        uses: actions/github-script@v3
+        uses: actions/github-script@v6
         if: needs.operator-ci.outputs.op_test_stream == 'community-operators' && needs.operator-ci.outputs.op_test_ci_yaml_only == '1'
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
-            github.issues.addLabels({
+            github.rest.issues.addLabels({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
diff --git a/ci/legacy/scripts/ci/actions-env b/ci/legacy/scripts/ci/actions-env
--- a/ci/legacy/scripts/ci/actions-env
+++ b/ci/legacy/scripts/ci/actions-env
@@ -55,8 +55,8 @@ echo "OP_TEST_RENAMED_FILES=$OP_TEST_RENAMED_FILES"
 echo "OP_TEST_REMOVED_FILES=$OP_TEST_REMOVED_FILES"
 echo "OP_TEST_LABELS=$OP_TEST_LABELS"
 
-echo "::set-output name=op_test_error_code::$OP_TEST_ERROR_CODE"
-echo "::set-output name=op_test_recreate::${OP_TEST_RECREATE}"
+echo "op_test_error_code=$OP_TEST_ERROR_CODE" >> $GITHUB_OUTPUT
+echo "op_test_recreate=${OP_TEST_RECREATE}" >> $GITHUB_OUTPUT
 
 
 for l in $(echo $OP_TEST_LABELS);do
@@ -67,24 +67,24 @@ for l in $(echo $OP_TEST_LABELS);do
   [[ "$l" = "allow/serious-changes-to-existing" ]] && export OP_TEST_ALLOW_SERIOUS_CHANGES=1
   
 done
-echo "::set-output name=op_test_recreate::${OP_TEST_RECREATE}"
+echo "op_test_recreate=${OP_TEST_RECREATE}" >> $GITHUB_OUTPUT
 
-[[ $OP_TEST_VER_OVERWRITE -eq 1 ]] && [[ $OP_TEST_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' is set. Only one label can be set !!! Exiting ..." ; echo "::set-output name=op_test_error_code::1"; exit 1; }
+[[ $OP_TEST_VER_OVERWRITE -eq 1 ]] && [[ $OP_TEST_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' is set. Only one label can be set !!! Exiting ..." ; echo "op_test_error_code=1" >> $GITHUB_OUTPUT; exit 1; }
 
 OP_TEST_CHANGES_OPERATOR=
 OP_TEST_CHANGES_OPERATOR_VERSIONS_MODIFIED=
 OP_TEST_CHANGES_OPERATOR_VERSIONS_REMOVED=
 
 
-echo "::set-output name=op_test_set_label_operator_version_overwrite::$OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE"
-echo "::set-output name=op_test_set_label_operator_recreate::$OP_TEST_SET_LABEL_OPERATOR_RECREATE"
-echo "::set-output name=op_test_is_modified::$OP_TEST_IS_MODIFIED"
-echo "::set-output name=op_test_modified_csvs::$OP_TEST_MODIFIED_CSVS"
-echo "::set-output name=op_test_allow_serious_changes::$OP_TEST_ALLOW_SERIOUS_CHANGES"
-echo "::set-output name=op_test_is_new_operatror::${OP_TEST_IS_NEW_OPERATOR}"
-echo "::set-output name=op_test_pr_title::${OP_TEST_PR_TITLE}"
-echo "::set-output name=op_test_update_graph::${OP_TEST_UPDATEGRAPH}"
-echo "::set-output name=op_test_authorized_changes::${OP_TEST_AUTHORIZED_CHANGES}"
+echo "op_test_set_label_operator_version_overwrite=$OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE" >> $GITHUB_OUTPUT
+echo "op_test_set_label_operator_recreate=$OP_TEST_SET_LABEL_OPERATOR_RECREATE" >> $GITHUB_OUTPUT
+echo "op_test_is_modified=$OP_TEST_IS_MODIFIED" >> $GITHUB_OUTPUT
+echo "op_test_modified_csvs=$OP_TEST_MODIFIED_CSVS" >> $GITHUB_OUTPUT
+echo "op_test_allow_serious_changes=$OP_TEST_ALLOW_SERIOUS_CHANGES" >> $GITHUB_OUTPUT
+echo "op_test_is_new_operatror=${OP_TEST_IS_NEW_OPERATOR}" >> $GITHUB_OUTPUT
+echo "op_test_pr_title=${OP_TEST_PR_TITLE}" >> $GITHUB_OUTPUT
+echo "op_test_update_graph=${OP_TEST_UPDATEGRAPH}" >> $GITHUB_OUTPUT
+echo "op_test_authorized_changes=${OP_TEST_AUTHORIZED_CHANGES}" >> $GITHUB_OUTPUT
 
 
 
@@ -129,29 +129,29 @@ if [ -n "$OP_TEST_REMOVED_FILES" ];then
 
     OP_TEST_READY=0
 
-    [[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 ]] && [[ $OP_TEST_CHANGES_STREAM_UPSTREAM -eq 1 ]] && { echo "Changes in both 'community-operators' and 'upstream-community-operators' dirs !!! Exiting ..."; echo "::set-output name=op_test_error_code::2"; exit 1; }
+    [[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 ]] && [[ $OP_TEST_CHANGES_STREAM_UPSTREAM -eq 1 ]] && { echo "Changes in both 'community-operators' and 'upstream-community-operators' dirs !!! Exiting ..."; echo "op_test_error_code=2" >> $GITHUB_OUTPUT; exit 1; }
 
-    echo "::set-output name=op_test_ready::${OP_TEST_READY}"
-    echo "::set-output name=op_release_ready::${OP_RELEASE_READY}"
-    echo "::set-output name=op_test_stream::${OP_TEST_STREAM_NAME}"
-    echo "::set-output name=op_test_name::${OP_TEST_OPERATOR_NAME}"
-    echo "::set-output name=op_test_version::${OP_TEST_OPERATOR_VERSION}"
-    echo "::set-output name=op_test_changed_ci_yaml::${OP_TEST_CI_YAML_CHANGED}"
-    echo "::set-output name=op_test_ver_overwrite::${OP_TEST_VER_OVERWRITE}"
-    echo "::set-output name=op_test_update_graph::${OP_TEST_UPDATEGRAPH}"
+    echo "op_test_ready=${OP_TEST_READY}" >> $GITHUB_OUTPUT
+    echo "op_release_ready=${OP_RELEASE_READY}" >> $GITHUB_OUTPUT
+    echo "op_test_stream=${OP_TEST_STREAM_NAME}" >> $GITHUB_OUTPUT
+    echo "op_test_name=${OP_TEST_OPERATOR_NAME}" >> $GITHUB_OUTPUT
+    echo "op_test_version=${OP_TEST_OPERATOR_VERSION}" >> $GITHUB_OUTPUT
+    echo "op_test_changed_ci_yaml=${OP_TEST_CI_YAML_CHANGED}" >> $GITHUB_OUTPUT
+    echo "op_test_ver_overwrite=${OP_TEST_VER_OVERWRITE}" >> $GITHUB_OUTPUT
+    echo "op_test_update_graph=${OP_TEST_UPDATEGRAPH}" >> $GITHUB_OUTPUT
     
     echo "Files removed only."
     if [ ! -d ${OP_TEST_STREAM_NAME}/${OP_TEST_OPERATOR_NAME} ];then
       OP_TEST_OP_DELETE=1
       DELETE_APPREG=1
       echo "op_release_delete_appreg=${DELETE_APPREG}"
-      echo "::set-output name=op_release_delete_appreg::${DELETE_APPREG}"
+      echo "op_release_delete_appreg=${DELETE_APPREG}" >> $GITHUB_OUTPUT
       echo "op_test_ready=${OP_TEST_READY}"
       echo "op_release_ready=${OP_RELEASE_READY}"
       echo "op_test_op_delete=$OP_TEST_OP_DELETE"
       echo "op_test_ver_overwrite=$OP_TEST_VER_OVERWRITE"
-      echo "::set-output name=op_test_op_delete::${OP_TEST_OP_DELETE}"
-      echo "::set-output name=op_test_is_modified::$OP_TEST_IS_MODIFIED"
+      echo "op_test_op_delete=${OP_TEST_OP_DELETE}" >> $GITHUB_OUTPUT
+      echo "op_test_is_modified=$OP_TEST_IS_MODIFIED" >> $GITHUB_OUTPUT
       echo "Directory '${OP_TEST_STREAM_NAME}/${OP_TEST_OPERATOR_NAME}' is removed. This is OK."
 
       exit 0
@@ -221,12 +221,12 @@ echo "OP_TEST_MODIFIED_OTHERS=$OP_TEST_MODIFIED_OTHERS"
 
 [[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 0 ]] && [[ $OP_TEST_CHANGES_STREAM_UPSTREAM -eq 0 ]] && [[ $OP_TEST_CI_YAML_CHANGED -eq 0 ]] && { echo "No changes 'community-operators' or 'upstream-community-operators' !!! Skipping test ..."; OP_TEST_READY=0; }
 
-[[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 ]] && [[ $OP_TEST_CHANGES_STREAM_UPSTREAM -eq 1 ]] && { echo "Changes in both 'community-operators' and 'upstream-community-operators' dirs !!! Exiting ..."; echo "::set-output name=op_test_error_code::2"; exit 1; }
+[[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 ]] && [[ $OP_TEST_CHANGES_STREAM_UPSTREAM -eq 1 ]] && { echo "Changes in both 'community-operators' and 'upstream-community-operators' dirs !!! Exiting ..."; echo "op_test_error_code=2" >> $GITHUB_OUTPUT; exit 1; }
 
-[[ $OP_TEST_CHANGES_GITHUB -eq 1 ]] && [[ $OP_TEST_ALLOW_CI_CHANGES -eq 0 ]] && { echo "Changes in '.github' dir, but 'allow/ci-changes' label is not set !!!"; echo "::set-output name=op_test_error_code::3"; OP_TEST_READY=0; exit 1; }
-[[ $OP_TEST_CHANGES_CI -eq 1 ]] && [[ $OP_TEST_ALLOW_CI_CHANGES -eq 0 ]] && { echo "Changes in ci, but 'allow/ci-changes' label is not set !!!"; echo "::set-output name=op_test_error_code::3"; OP_TEST_READY=0; exit 1; }
-[[ $OP_TEST_CHANGES_DOCS -eq 1 ]] && [[ $OP_TEST_ALLOW_CI_CHANGES -eq 0 ]] && { echo "Changes in docs, but 'allow/ci-changes' label is not set !!!"; echo "::set-output name=op_test_error_code::3"; OP_TEST_READY=0; exit 1; }
-[[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 || $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 ]] && [[ $OP_TEST_READY -eq 0 ]] && { echo "Error: Operator changes detected with ci changes and 'allow/ci-changes' is not set !!! Exiting ..."; echo "::set-output name=op_test_error_code::3";  exit 1; }
+[[ $OP_TEST_CHANGES_GITHUB -eq 1 ]] && [[ $OP_TEST_ALLOW_CI_CHANGES -eq 0 ]] && { echo "Changes in '.github' dir, but 'allow/ci-changes' label is not set !!!"; echo "op_test_error_code=3" >> $GITHUB_OUTPUT; OP_TEST_READY=0; exit 1; }
+[[ $OP_TEST_CHANGES_CI -eq 1 ]] && [[ $OP_TEST_ALLOW_CI_CHANGES -eq 0 ]] && { echo "Changes in ci, but 'allow/ci-changes' label is not set !!!"; echo "op_test_error_code=3" >> $GITHUB_OUTPUT; OP_TEST_READY=0; exit 1; }
+[[ $OP_TEST_CHANGES_DOCS -eq 1 ]] && [[ $OP_TEST_ALLOW_CI_CHANGES -eq 0 ]] && { echo "Changes in docs, but 'allow/ci-changes' label is not set !!!"; echo "op_test_error_code=3" >> $GITHUB_OUTPUT; OP_TEST_READY=0; exit 1; }
+[[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 || $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 ]] && [[ $OP_TEST_READY -eq 0 ]] && { echo "Error: Operator changes detected with ci changes and 'allow/ci-changes' is not set !!! Exiting ..."; echo "op_test_error_code=3" >> $GITHUB_OUTPUT;  exit 1; }
 [[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 0 && $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 0 ]] && [[ $OP_TEST_READY -eq 0 ]] && { echo "Nothing to test"; exit 0; }
 
 [[ $OP_TEST_CHANGES_STREAM_COMMUNITY -eq 1 ]] && OP_TEST_STREAM_NAME="community-operators"
@@ -250,7 +250,7 @@ OP_TEST_OPERATOR_VERSIONS=
 for v in $VERSIONS;do
   TMP_OP_NAME=$(echo $v | cut -d '/' -f 2)
   OP_TEST_OPERATOR_VERSIONS="$(echo $v| cut -d '/' -f 3) $OP_TEST_OPERATOR_VERSIONS"
-  [ "$OP_TEST_OPERATOR_NAME" = "$TMP_OP_NAME" ] || { echo "Error: Multiple operators are changed !!! Detected:'$OP_TEST_OPERATOR_NAME' and '$TMP_OP_NAME' !!! Exiting ..."; OP_TEST_READY=0; echo "::set-output name=op_test_error_code::5";  exit 1;  }
+  [ "$OP_TEST_OPERATOR_NAME" = "$TMP_OP_NAME" ] || { echo "Error: Multiple operators are changed !!! Detected:'$OP_TEST_OPERATOR_NAME' and '$TMP_OP_NAME' !!! Exiting ..."; OP_TEST_READY=0; echo "op_test_error_code=5" >> $GITHUB_OUTPUT;  exit 1;  }
 done
 # remove trailing space
 OP_TEST_OPERATOR_VERSIONS=$(echo $OP_TEST_OPERATOR_VERSIONS | sed 's/ *$//g')
@@ -286,7 +286,7 @@ OP_TEST_OPERATOR_VERSIONS_ALL_COUNT=0
 
 echo "Versions Count: CHANGED[$OP_TEST_OPERATOR_VERSIONS] REMOVED[$OP_TEST_OPERATOR_VERSIONS_REMOVED]"
 
-# [[ $OPRT -eq 1 ]] && [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "::set-output name=op_test_error_code::6"; exit 1;  }
+# [[ $OPRT -eq 1 ]] && [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "op_test_error_code=6" >> $GITHUB_OUTPUT; exit 1;  }
 # [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -eq 1 ]] && [[ $OP_TEST_IS_MODIFIED -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_REMOVED_COUNT -gt 0 ]] && OP_TEST_SET_LABEL_OPERATOR_RECREATE=1 && OP_TEST_RECREATE=1 && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=0 && OP_TEST_VER_OVERWRITE=0
 
 [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -eq 1 ]] && [[ $OP_TEST_IS_MODIFIED -eq 1 ]] && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=1
@@ -295,15 +295,15 @@ echo "Versions Count: CHANGED[$OP_TEST_OPERATOR_VERSIONS] REMOVED[$OP_TEST_OPERA
 [[ $OP_TEST_OPERATOR_VERSIONS_REMOVED_COUNT -gt 0 ]] && OP_TEST_SET_LABEL_OPERATOR_RECREATE=1 && OP_TEST_RECREATE=1 && OP_TEST_OP_DELETE=1 && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=0 && OP_TEST_VER_OVERWRITE=0
 [[ $OP_TEST_OPERATOR_VERSIONS_ALL_COUNT -eq 1 ]] && OP_TEST_IS_NEW_OPERATOR=1 && OP_TEST_RECREATE=1 && OP_TEST_SET_LABEL_OPERATOR_RECREATE=1 && OP_TEST_VER_OVERWRITE=0 && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=0
 
-# [[ $OPRT -eq 0 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -gt 1 ]] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && { echo "Error: Multiple versions [$OP_TEST_OPERATOR_VERSIONS] were modified and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "::set-output name=op_test_error_code::5"; exit 1;  }
+# [[ $OPRT -eq 0 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -gt 1 ]] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && { echo "Error: Multiple versions [$OP_TEST_OPERATOR_VERSIONS] were modified and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "op_test_error_code=5" >> $GITHUB_OUTPUT; exit 1;  }
 
 
-[[ $OP_TEST_VER_OVERWRITE -eq 1 ]] && [[ $OP_TEST_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' is set. Only one label can be set !!! Exiting ..."; echo "::set-output name=op_test_error_code::1"; exit 1; }
+[[ $OP_TEST_VER_OVERWRITE -eq 1 ]] && [[ $OP_TEST_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' is set. Only one label can be set !!! Exiting ..."; echo "op_test_error_code=1" >> $GITHUB_OUTPUT; exit 1; }
 
-# [[ $OPRT -eq 1 ]] && [[ $OP_TEST_CI_YAML_MODIFIED -eq 1 ]] && [[ $OP_TEST_CI_YAML_ONLY -eq 0 ]] && { echo "We support only a single file modification in case of 'ci.yaml' file. If you want to update it, please make an extra PR with 'ci.yaml' file modification only !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/."; echo "::set-output name=op_test_error_code::7"; exit 1; }
+# [[ $OPRT -eq 1 ]] && [[ $OP_TEST_CI_YAML_MODIFIED -eq 1 ]] && [[ $OP_TEST_CI_YAML_ONLY -eq 0 ]] && { echo "We support only a single file modification in case of 'ci.yaml' file. If you want to update it, please make an extra PR with 'ci.yaml' file modification only !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/."; echo "op_test_error_code=7" >> $GITHUB_OUTPUT; exit 1; }
 
-echo "::set-output name=op_test_stream::${OP_TEST_STREAM_NAME}"
-echo "::set-output name=op_test_name::${OP_TEST_OPERATOR_NAME}"
+echo "op_test_stream=${OP_TEST_STREAM_NAME}" >> $GITHUB_OUTPUT
+echo "op_test_name=${OP_TEST_OPERATOR_NAME}" >> $GITHUB_OUTPUT
 
 yq --version || { echo "Command 'yq' could not be found !!!"; exit 1; } 
 
@@ -335,11 +335,11 @@ fi
 if [[ $OP_TEST_READY -eq 1 ]];then
   if [ -f $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml ];then 
     TEST_REVIEWERS=$(cat $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml | yq '.reviewers')
-    # [ "$TEST_REVIEWERS" == "null" ] &&  { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' contains 'reviewers' array field with one reviewer set as minimum !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/ !!!"; echo "::set-output name=op_test_error_code::4"; exit 1; }
+    # [ "$TEST_REVIEWERS" == "null" ] &&  { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' contains 'reviewers' array field with one reviewer set as minimum !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/ !!!"; echo "op_test_error_code=4" >> $GITHUB_OUTPUT; exit 1; }
     
     if [ "$TEST_REVIEWERS" != "null" ];then
       TEST_REVIEWERS=$(cat $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml | yq '.reviewers | length' || echo 0)
-      [[ $TEST_REVIEWERS -eq 0 ]] && { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' contains 'reviewers' array field and it has at least one reviewer set!!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/ !!!"; echo "::set-output name=op_test_error_code::4"; exit 1; }
+      [[ $TEST_REVIEWERS -eq 0 ]] && { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' contains 'reviewers' array field and it has at least one reviewer set!!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/ !!!"; echo "op_test_error_code=4" >> $GITHUB_OUTPUT; exit 1; }
     else
       echo "File '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' doesn't contain 'reviewers' array field !!! If one wants to add reviewers (truested-authors) More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/. !!!"
       OP_TEST_ERROR_CODE=10
@@ -396,34 +396,29 @@ echo "op_test_dockerfile_changed=$OP_TEST_CHANGES_DOCKERFILE"
 echo "op_test_error_code=$OP_TEST_ERROR_CODE"
 echo "op_test_authorized_changes=$OP_TEST_AUTHORIZED_CHANGES"
 
-echo "::set-output name=op_test_ready::${OP_TEST_READY}"
-echo "::set-output name=op_release_ready::${OP_RELEASE_READY}"
-
-echo "::set-output name=op_test_stream::${OP_TEST_STREAM_NAME}"
-echo "::set-output name=op_test_name::${OP_TEST_OPERATOR_NAME}"
-echo "::set-output name=op_test_version::${OP_TEST_OPERATOR_VERSION}"
-echo "::set-output name=op_test_versions::${OP_TEST_OPERATOR_VERSIONS}"
-echo "::set-output name=op_test_is_new_operatror::${OP_TEST_IS_NEW_OPERATOR}"
-echo "::set-output name=op_test_pr_title::${OP_TEST_PR_TITLE}"
-echo "::set-output name=op_test_pr_revievers::${OP_TEST_REVIEVERS}"
-
-
-echo "::set-output name=op_test_ci_yaml_only::${OP_TEST_CI_YAML_ONLY}"
-echo "::set-output name=op_test_ci_yaml_changed::${OP_TEST_CI_YAML_CHANGED}"
-
-echo "::set-output name=op_test_op_delete::${OP_TEST_OP_DELETE}"
-echo "::set-output name=op_test_ver_overwrite::${OP_TEST_VER_OVERWRITE}"
-echo "::set-output name=op_test_recreate::${OP_TEST_RECREATE}"
-echo "::set-output name=op_test_update_graph::${OP_TEST_UPDATEGRAPH}"
-
-echo "::set-output name=op_test_set_label_operator_version_overwrite::$OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE"
-echo "::set-output name=op_test_set_label_operator_recreate::$OP_TEST_SET_LABEL_OPERATOR_RECREATE"
-echo "::set-output name=op_test_is_modified::$OP_TEST_IS_MODIFIED"
-echo "::set-output name=op_test_modified_csvs::$OP_TEST_MODIFIED_CSVS"
-echo "::set-output name=op_test_modified_others::$OP_TEST_MODIFIED_OTHERS"
-echo "::set-output name=op_test_error_code::$OP_TEST_ERROR_CODE"
-echo "::set-output name=op_test_authorized_changes::${OP_TEST_AUTHORIZED_CHANGES}"
-echo "::set-output name=op_test_dockerfile_changed::$OP_TEST_CHANGES_DOCKERFILE"
+echo "op_test_ready=${OP_TEST_READY}" >> $GITHUB_OUTPUT
+echo "op_release_ready=${OP_RELEASE_READY}" >> $GITHUB_OUTPUT
+echo "op_test_stream=${OP_TEST_STREAM_NAME}" >> $GITHUB_OUTPUT
+echo "op_test_name=${OP_TEST_OPERATOR_NAME}" >> $GITHUB_OUTPUT
+echo "op_test_version=${OP_TEST_OPERATOR_VERSION}" >> $GITHUB_OUTPUT
+echo "op_test_versions=${OP_TEST_OPERATOR_VERSIONS}" >> $GITHUB_OUTPUT
+echo "op_test_is_new_operatror=${OP_TEST_IS_NEW_OPERATOR}" >> $GITHUB_OUTPUT
+echo "op_test_pr_title=${OP_TEST_PR_TITLE}" >> $GITHUB_OUTPUT
+echo "op_test_pr_revievers=${OP_TEST_REVIEVERS}" >> $GITHUB_OUTPUT
+echo "op_test_ci_yaml_only=${OP_TEST_CI_YAML_ONLY}" >> $GITHUB_OUTPUT
+echo "op_test_ci_yaml_changed=${OP_TEST_CI_YAML_CHANGED}" >> $GITHUB_OUTPUT
+echo "op_test_op_delete=${OP_TEST_OP_DELETE}" >> $GITHUB_OUTPUT
+echo "op_test_ver_overwrite=${OP_TEST_VER_OVERWRITE}" >> $GITHUB_OUTPUT
+echo "op_test_recreate=${OP_TEST_RECREATE}" >> $GITHUB_OUTPUT
+echo "op_test_update_graph=${OP_TEST_UPDATEGRAPH}" >> $GITHUB_OUTPUT
+echo "op_test_set_label_operator_version_overwrite=$OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE" >> $GITHUB_OUTPUT
+echo "op_test_set_label_operator_recreate=$OP_TEST_SET_LABEL_OPERATOR_RECREATE" >> $GITHUB_OUTPUT
+echo "op_test_is_modified=$OP_TEST_IS_MODIFIED" >> $GITHUB_OUTPUT
+echo "op_test_modified_csvs=$OP_TEST_MODIFIED_CSVS" >> $GITHUB_OUTPUT
+echo "op_test_modified_others=$OP_TEST_MODIFIED_OTHERS" >> $GITHUB_OUTPUT
+echo "op_test_error_code=$OP_TEST_ERROR_CODE" >> $GITHUB_OUTPUT
+echo "op_test_authorized_changes=${OP_TEST_AUTHORIZED_CHANGES}" >> $GITHUB_OUTPUT
+echo "op_test_dockerfile_changed=$OP_TEST_CHANGES_DOCKERFILE" >> $GITHUB_OUTPUT
 
 
 
