Upgrade CI (23 Jan 2022 09:22:57)

diff --git a/.github/workflows/operator_test.yaml b/.github/workflows/operator_test.yaml
--- a/.github/workflows/operator_test.yaml
+++ b/.github/workflows/operator_test.yaml
@@ -90,7 +90,7 @@ jobs:
           echo "::set-output name=opp_check_err_k8s_bundles::0"
           echo "::set-output name=opp_check_err_k8s_bundles_value::"
           [ -f /tmp/operator-test/op_failed_k8s_bundles.yaml ] && echo "::set-output name=opp_check_err_k8s_bundles::1" || true
-          [ -f /tmp/operator-test/op_failed_k8s_bundles.yaml ] && echo "::set-output name=opp_check_err_k8s_bundles_value::$(cat /tmp/operator-test/op_failed_k8s_bundles.yaml | yq -r '.operators')" || true
+          [ -f /tmp/operator-test/op_failed_k8s_bundles.yaml ] && echo "::set-output name=opp_check_err_k8s_bundles_value::$(cat /tmp/operator-test/op_failed_k8s_bundles.yaml | yq -r '.operators' | @csv' | tr -d '"')" || true
       - name: Operator info (comment)
         id: op-info-comment
         if: always() && steps.op-info-result.outputs.opp_check_err_k8s_bundles == '1'
@@ -98,10 +98,7 @@ jobs:
         with:
           message: |
             Dear @${{ github.event.pull_request.user.login }},
-            Some operators are using deprecated api and setting kubernetes max versions in annotation `operatorhub.io/ui-metadata-max-k8s-version` in CSV file. Here is list of affected versions
-            ```
-            ${{ steps.op-info-result.outputs.opp_check_err_k8s_bundles_value }}
-            ```
+            Some operators are using deprecated api and setting kubernetes max versions in annotation `operatorhub.io/ui-metadata-max-k8s-version` in CSV file. Affected versions : `${{ steps.op-info-result.outputs.opp_check_err_k8s_bundles_value }}`
             TODO: More info [here](https://redhat-openshift-ecosystem.github.io/community-operators-pipeline/operator-ci-yaml/#automatic-cluster-version-label-ocp-packagemanifest-only).
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
