Upgrade CI (11 Aug 2023 13:21:12)

diff --git a/.github/workflows/operator_workflow_complete.yaml b/.github/workflows/operator_workflow_complete.yaml
--- a/.github/workflows/operator_workflow_complete.yaml
+++ b/.github/workflows/operator_workflow_complete.yaml
@@ -7,7 +7,7 @@ on:
     types: [completed]
 
 env:
-  OPP_PRODUCTION_TYPE: "k8s"
+  OPP_PRODUCTION_TYPE: "ocp"
 
 
 jobs:
@@ -39,7 +39,8 @@ jobs:
       - name: 'PR Number'
         id: pr-number
         run: |
-          PR=$(cat ./NR)
+          PR=$(tr -dc [0-9] <./NR)
+          [ -z "$PR" ] && echo "Invalid PR number" && exit 1
           echo "pr=${PR}" >> $GITHUB_OUTPUT
 
       - uses: actions/github-script@v6
@@ -73,11 +74,13 @@ jobs:
       - uses: actions/github-script@v6
         id: pr-labels
         continue-on-error: true
+        env:
+          PR: "${{ needs.pr.outputs.pr }}"
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: | 
             const labels = await github.rest.issues.listLabelsOnIssue({
-              issue_number: ${{ needs.pr.outputs.pr }},
+              issue_number: process.env.PR,
               owner: context.repo.owner,
               repo: context.repo.repo
             })
@@ -86,11 +89,13 @@ jobs:
       - name: "Setting package-validated label"
         uses: actions/github-script@v6
         continue-on-error: true
+        env:
+          PR: "${{ needs.pr.outputs.pr }}"
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
             github.rest.issues.addLabels({
-              issue_number: ${{ needs.pr.outputs.pr }},
+              issue_number: process.env.PR,
               owner: context.repo.owner,
               repo: context.repo.repo,
               labels: ['package-validated']
@@ -100,38 +105,13 @@ jobs:
           (!contains(fromJson(steps.pr-labels.outputs.result).*.name, 'do-not-merge/work-in-progress')) &&
           (!contains(fromJson(steps.pr-labels.outputs.result).*.name, 'do-not-merge/hold'))
         continue-on-error: true
+        env:
+          PR: "${{ needs.pr.outputs.pr }}"
         with:
           github-token: ${{ secrets.FRAMEWORK_MERGE }}
           script: |
             github.rest.issues.createComment({
-              issue_number: ${{ needs.pr.outputs.pr }},
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: '/merge possible'
-            })
-
-      - name: "Set installation-validated"
-        uses: actions/github-script@v6
-        continue-on-error: true
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
-          script: |
-            github.rest.issues.addLabels({
-              issue_number: ${{ needs.pr.outputs.pr }},
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              labels: ['installation-validated']
-            })
-      - uses: actions/github-script@v6
-        if: |
-          (!contains(fromJson(steps.pr-labels.outputs.result).*.name, 'do-not-merge/work-in-progress')) &&
-          (!contains(fromJson(steps.pr-labels.outputs.result).*.name, 'do-not-merge/hold'))
-        continue-on-error: true
-        with:
-          github-token: ${{ secrets.FRAMEWORK_MERGE }}
-          script: |
-            github.rest.issues.createComment({
-              issue_number: ${{ needs.pr.outputs.pr }},
+              issue_number: process.env.PR,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: '/merge possible'
@@ -146,11 +126,13 @@ jobs:
         if: needs.pr.outputs.pr != '0'
         uses: actions/github-script@v6
         continue-on-error: true
+        env:
+          PR: "${{ needs.pr.outputs.pr }}"
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
             github.rest.issues.removeLabel({
-              issue_number: ${{ needs.pr.outputs.pr }},
+              issue_number: process.env.PR,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'package-validated'
@@ -159,11 +141,13 @@ jobs:
         if: needs.pr.outputs.pr != '0'
         uses: actions/github-script@v6
         continue-on-error: true
+        env:
+          PR: "${{ needs.pr.outputs.pr }}"
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
             github.rest.issues.removeLabel({
-              issue_number: ${{ needs.pr.outputs.pr }},
+              issue_number: process.env.PR,
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: 'installation-validated'
