Upgrade CI (12 Sep 2022 08:49:54)

diff --git a/.github/workflows/operator_release.yaml b/.github/workflows/operator_release.yaml
--- a/.github/workflows/operator_release.yaml
+++ b/.github/workflows/operator_release.yaml
@@ -29,7 +29,7 @@ env:
   OPP_ANSIBLE_PULL_BRANCH: "upstream-community-dev"
   OPP_PROD: 1
   OPP_MIRROR_LATEST_TAG: ""
-  OPP_PRODUCTION_TYPE: "k8s"
+  OPP_PRODUCTION_TYPE: "ocp"
   OPP_RELEASE_BUNDLE_REGISTRY: "quay.io"
   OPP_RELEASE_BUNDLE_ORGANIZATION: "community-operators-pipeline"
   OPP_RELEASE_INDEX_REGISTRY: "quay.io"
@@ -39,16 +39,16 @@ env:
   OPP_MIRROR_INDEX_ORGANIZATION: "community-operators-pipeline"
   OPP_MIRROR_INDEX_NAME: "catalog"
   OPP_MIRROR_INDEX_ENABLED: "1"
-  OPP_MIRROR_INDEX_MULTIARCH_BASE: "quay.io/operator-framework/opm"
-  OPP_MULTIARCH_SUPPORTED_VERSIONS: "latest"
+  OPP_MIRROR_INDEX_MULTIARCH_BASE: "registry.redhat.io/openshift4/ose-operator-registry"
+  OPP_MULTIARCH_SUPPORTED_VERSIONS: "v4.5 v4.6 v4.7 v4.8 v4.9 v4.10 v4.11"
   OPP_MIRROR_INDEX_MULTIARCH_POSTFIX: "s"
   IIB_INPUT_REGISTRY_USER: "mavala"
   OPP_REGISTRY_MIRROR_USER: "mavala"
   OPP_THIS_REPO_BASE: "https://github.com"
   OPP_THIS_REPO: "redhat-openshift-ecosystem/community-operators-pipeline"
   OPP_THIS_BRANCH: "main"
-  INDEX_PATH_TO_SIGN: "not-defined"
-  SIGNATURE_ENDPOINT: "https://not-defined"
+  INDEX_PATH_TO_SIGN: "quay.io/community-operators-pipeline/catalog"
+  SIGNATURE_ENDPOINT: "https://community-signing-pipeline-dev.apps.pipelines-stage.0ce8.p1.openshiftapps.com"
   OPP_REVIEWERS_ENABLED: 0
 
 
@@ -118,15 +118,15 @@ jobs:
       opp_release_delete_appreg: "${{ steps.op-traffic-light.outputs.opp_release_delete_appreg }}"
       opp_pr_title: "${{ steps.op-traffic-light.outputs.opp_pr_title }}"
       opp_auto_packagemanifest_cluster_version_label: "${{ steps.op-traffic-light.outputs.opp_auto_packagemanifest_cluster_version_label }}"
-  remove-k8s:
-    name: "Remove / k8s"
+  remove-ocp:
+    name: "Remove / ocp"
 
     needs: pr-check
     if: needs.pr-check.outputs.opp_release_ready == '1'
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        index-tag: ['latest-db']
+        index-tag: ['v4.6-db', 'v4.7-db', 'v4.8-db', 'v4.9-db', 'v4.10-db', 'v4.11']
 
       fail-fast: false
     steps:
@@ -149,6 +149,7 @@ jobs:
           OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
           OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
           OPP_IIB_INSTALL: 0
+          IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
           OPERATOR_INDEX_TAG: ${{ matrix.index-tag }}
         run: |
           echo "OPP_LABELS=$OPP_LABELS"
@@ -159,9 +160,9 @@ jobs:
           echo "op_delete_${OPERATOR_INDEX_TAG} operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH"
           bash <(curl -sL $OPP_SCRIPT_URL) op_delete_${OPERATOR_INDEX_TAG} operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH || $FAKE_RC
 
-  operators-k8s:
-    name: "Index check / k8s"
-    needs: [pr-check, remove-k8s ]
+  operators-ocp:
+    name: "Index check / ocp"
+    needs: [pr-check, remove-ocp ]
 
     if: needs.pr-check.outputs.opp_release_ready == '1' && (needs.pr-check.outputs.opp_op_delete == '0' || needs.pr-check.outputs.opp_is_new_operatror == '1' || needs.pr-check.outputs.opp_recreate == '1' )
     runs-on: ubuntu-latest
@@ -173,7 +174,7 @@ jobs:
           OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
           OPP_IIB_INSTALL: 0
           IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
-          OPERATOR_INDEX_TAG: "orange_latest"
+          OPERATOR_INDEX_TAG: "orange_v4.6 orange_v4.7 orange_v4.8 orange_v4.9 orange_v4.10 orange_v4.11"
 
           OPP_INDEX_CHECK_ONLY: 1
         run: |
@@ -185,7 +186,12 @@ jobs:
       - name: Index check
         run: |
           echo "Operators : ${{ steps.operators.outputs.opp_uncomplete_operators }}"
-          echo "Operators (latest) : ${{ steps.operators.outputs.opp_uncomplete_operators_latest }}"
+          echo "Operators (v4.6) : ${{ steps.operators.outputs.opp_uncomplete_operators_v4_6 }}"
+          echo "Operators (v4.7) : ${{ steps.operators.outputs.opp_uncomplete_operators_v4_7 }}"
+          echo "Operators (v4.8) : ${{ steps.operators.outputs.opp_uncomplete_operators_v4_8 }}"
+          echo "Operators (v4.9) : ${{ steps.operators.outputs.opp_uncomplete_operators_v4_9 }}"
+          echo "Operators (v4.10) : ${{ steps.operators.outputs.opp_uncomplete_operators_v4_10 }}"
+          echo "Operators (v4.11) : ${{ steps.operators.outputs.opp_uncomplete_operators_v4_11 }}"
 
       - name: Operator info
         id: op-info
@@ -201,7 +207,7 @@ jobs:
           OPP_FORCE_OPERATORS=${OPP_FORCE_OPERATORS// /,}
           echo $OPP_FORCE_OPERATORS
           [ "$OPP_AUTO_LABEL" = '1' ] && ANSIBLE_ARGS="-e automatic_cluster_version_label=true" || ANSIBLE_ARGS="-e automatic_cluster_version_label=false"
-          ansible-pull -U $OPP_ANSIBLE_PULL_REPO -C $OPP_ANSIBLE_PULL_BRANCH -i localhost, -e run_upstream=true -e run_prepare_catalog_repo_upstream=true -e catalog_repo=$OPP_THIS_REPO_BASE/$OPP_THIS_REPO -e catalog_repo_branch=$OPP_THIS_BRANCH upstream/local.yml --tags reset_tools,operator_info -e operator_base_dir=/tmp/community-operators-for-catalog/operators -e operators=$OPP_FORCE_OPERATORS -e cluster_type=$OPP_PRODUCTION_TYPE -e strict_cluster_version_labels=true -e production_registry_namespace=$OPP_RELEASE_BUNDLE_REGISTRY/$OPP_RELEASE_BUNDLE_ORGANIZATION $ANSIBLE_ARGS
+          ansible-pull -U $OPP_ANSIBLE_PULL_REPO -C $OPP_ANSIBLE_PULL_BRANCH -i localhost, -e run_upstream=true -e run_prepare_catalog_repo_upstream=true -e catalog_repo=$OPP_THIS_REPO_BASE/$OPP_THIS_REPO -e catalog_repo_branch=$OPP_THIS_BRANCH upstream/local.yml --tags reset_tools,operator_info -e operator_base_dir=/tmp/community-operators-for-catalog/operators -e operators=$OPP_FORCE_OPERATORS -e cluster_type=$OPP_PRODUCTION_TYPE -e strict_cluster_version_labels=true -e stream_kind=openshift_upstream -e production_registry_namespace=$OPP_RELEASE_BUNDLE_REGISTRY/$OPP_RELEASE_BUNDLE_ORGANIZATION $ANSIBLE_ARGS
       - name: Upload operator_info
         uses: actions/upload-artifact@v2
         with:
@@ -217,11 +223,17 @@ jobs:
           [ -f /tmp/operator-test/op_info.yaml ] && cat /tmp/operator-test/op_info.yaml || echo "::set-output name=opp_uncomplete_operators::"          
     outputs:
       opp_uncomplete_operators: "${{ steps.operators.outputs.opp_uncomplete_operators }}"
-      opp_uncomplete_operators_latest: "${{ steps.operators.outputs.opp_uncomplete_operators_latest }}"
-  bundles-k8s:
-    name: "Bundles / k8s"
-    needs: [ pr-check, remove-k8s, operators-k8s ]
-    if: needs.pr-check.outputs.opp_release_ready == '1' && needs.operators-k8s.outputs.opp_uncomplete_operators != ''
+      opp_uncomplete_operators_v4_6: "${{ steps.operators.outputs.opp_uncomplete_operators_v4_6 }}"
+      opp_uncomplete_operators_v4_7: "${{ steps.operators.outputs.opp_uncomplete_operators_v4_7 }}"
+      opp_uncomplete_operators_v4_8: "${{ steps.operators.outputs.opp_uncomplete_operators_v4_8 }}"
+      opp_uncomplete_operators_v4_9: "${{ steps.operators.outputs.opp_uncomplete_operators_v4_9 }}"
+      opp_uncomplete_operators_v4_10: "${{ steps.operators.outputs.opp_uncomplete_operators_v4_10 }}"
+      opp_uncomplete_operators_v4_11: "${{ steps.operators.outputs.opp_uncomplete_operators_v4_11 }}"
+
+  bundles-ocp:
+    name: "Bundles / ocp"
+    needs: [ pr-check, remove-ocp, operators-ocp ]
+    if: needs.pr-check.outputs.opp_release_ready == '1' && needs.operators-ocp.outputs.opp_uncomplete_operators != ''
 
     runs-on: ubuntu-latest
     steps:
@@ -240,9 +252,10 @@ jobs:
           OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
           OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
           OPP_IIB_INSTALL: 0
+          IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
           OPERATOR_INDEX_TAG: latest
           OPP_SKIP_INDEX: 1
-          OPP_FORCE_OPERATORS: "${{ needs.operators-k8s.outputs.opp_uncomplete_operators }}"
+          OPP_FORCE_OPERATORS: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators }}"
 
         run: |
           echo "OPP_LABELS=$OPP_LABELS"
@@ -253,15 +266,15 @@ jobs:
           echo "orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH"
           bash <(curl -sL $OPP_SCRIPT_URL) orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH || $FAKE_RC
 
-  release-k8s:
-    name: "Index / k8s"
-    needs: [ pr-check, operators-k8s, bundles-k8s ]
-    if: needs.pr-check.outputs.opp_release_ready == '1' && needs.operators-k8s.outputs.opp_uncomplete_operators != ''
+  release-ocp:
+    name: "Index / ocp"
+    needs: [ pr-check, operators-ocp, bundles-ocp ]
+    if: needs.pr-check.outputs.opp_release_ready == '1' && needs.operators-ocp.outputs.opp_uncomplete_operators != ''
 
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        index-tag: ['latest-db']
+        index-tag: ['v4.6-db', 'v4.7-db', 'v4.8-db', 'v4.9-db', 'v4.10-db', 'v4.11']
 
       fail-fast: false
     steps:
@@ -280,13 +293,19 @@ jobs:
           OPP_LABELS: "${{ needs.pr-check.outputs.opp_labels }}"
           OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
           OPP_IIB_INSTALL: 1
-          #OPP_MIRROR_INDEX_ENABLED: 0
+
           OPP_FORCE_INDEX_UPDATE: 1
           IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
+          IIB_OUTPUT_REGISTRY_TOKEN: ${{ secrets.IIB_OUTPUT_REGISTRY_TOKEN }}
           OPERATOR_INDEX_TAG: ${{ matrix.index-tag }}
-          # OPP_FORCE_OPERATORS: "${{ needs.operators-k8s.outputs.opp_uncomplete_operators }}"
+          # OPP_FORCE_OPERATORS: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators }}"
           OPP_FORCE_OPERATORS: ""
-          OPP_FORCE_OPERATORS_latest: "${{ needs.operators-k8s.outputs.opp_uncomplete_operators_latest }}"
+          OPP_FORCE_OPERATORS_v4_6: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators_v4_6 }}"
+          OPP_FORCE_OPERATORS_v4_7: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators_v4_7 }}"
+          OPP_FORCE_OPERATORS_v4_8: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators_v4_8 }}"
+          OPP_FORCE_OPERATORS_v4_9: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators_v4_9 }}"
+          OPP_FORCE_OPERATORS_v4_10: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators_v4_10 }}"
+          OPP_FORCE_OPERATORS_v4_11: "${{ needs.operators-ocp.outputs.opp_uncomplete_operators_v4_11 }}"
 
         run: |
           echo "OPP_LABELS=$OPP_LABELS"
@@ -296,3 +315,113 @@ jobs:
 
           echo "orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH"
           bash <(curl -sL $OPP_SCRIPT_URL) orange_${OPERATOR_INDEX_TAG} operators/sync $OPP_THIS_REPO $OPP_THIS_BRANCH || $FAKE_RC
+
+      - name: Sign index
+        id: openshift-vars
+        env:
+          OPERATOR_INDEX_TAG_RAW: ${{ matrix.index-tag }}
+          OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
+        run: |
+          docker login ${OPP_MIRROR_INDEX_REGISTRY} -u $OPP_REGISTRY_MIRROR_USER -p $REGISTRY_MIRROR_PW
+          OPERATOR_INDEX_TAG=$(echo ${OPERATOR_INDEX_TAG_RAW} |cut -d'-' -f1)
+          echo "OPERATOR_INDEX_TAG=$OPERATOR_INDEX_TAG"
+          OPERATOR_INDEX="${INDEX_PATH_TO_SIGN}:${OPERATOR_INDEX_TAG}"
+          MANIFEST_LIST=${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}:${OPERATOR_INDEX_TAG}
+          echo "MANIFEST_LIST=$MANIFEST_LIST"
+          INDIVIDUAL_IMAGE_MANIFESTS=$(docker manifest inspect $MANIFEST_LIST|jq '.manifests[]|.digest'|tr -d '"')
+          echo "INDIVIDUAL_IMAGE_MANIFESTS=$INDIVIDUAL_IMAGE_MANIFESTS"
+          INDIVIDUAL_IMAGE_MANIFESTS_COUNT=$(echo $INDIVIDUAL_IMAGE_MANIFESTS| sed 's/[^ ]//g' | wc -c)
+          echo "INDIVIDUAL_IMAGE_MANIFESTS_COUNT=$INDIVIDUAL_IMAGE_MANIFESTS_COUNT"
+          
+          for ITERATE_OVER_MANIFESTS in $(seq 1 $INDIVIDUAL_IMAGE_MANIFESTS_COUNT); do
+            echo $ITERATE_OVER_MANIFESTS
+            OPERATOR_INDEX_DIGEST=$(echo $INDIVIDUAL_IMAGE_MANIFESTS|cut -d " " -f${ITERATE_OVER_MANIFESTS})
+            echo "OPERATOR_INDEX_DIGEST=$OPERATOR_INDEX_DIGEST"
+            SIGNATURE_PAYLOAD="{\"manifest_digest\": \"${OPERATOR_INDEX_DIGEST}\", \"reference\": \"${OPERATOR_INDEX}\",\"requester\": \"${{ secrets.SIGNATURE_WEBHOOK_REQUESTER_EMAIL }}\"}"
+            echo ${SIGNATURE_PAYLOAD}
+            curl --connect-timeout 10 --max-time 20 --retry 5 --retry-delay 0 --retry-max-time 100 \
+            ${SIGNATURE_ENDPOINT} -d "${SIGNATURE_PAYLOAD}" -u "community-op-cert:${{ secrets.SIGNATURE_WEBHOOK_PASSWD }}"
+          done
+
+          # skopeo inspect docker://$MANIFEST_LIST > /dev/null # error out if needed
+          # OPERATOR_INDEX_DIGEST=$(skopeo inspect docker://$MANIFEST_LIST | jq -r ".Digest")
+          #OPERATOR_INDEX_RESOLVED="${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}@${OPERATOR_INDEX_DIGEST}"
+          
+          
+      # - name: Prepare variables for the sign process
+      #   id: openshift-vars
+      #   env:
+      #     OPERATOR_INDEX_TAG_RAW: ${{ matrix.index-tag }}
+      #     OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
+      #   run: |
+      #     docker login ${OPP_MIRROR_INDEX_REGISTRY} -u $OPP_REGISTRY_MIRROR_USER -p $REGISTRY_MIRROR_PW
+      #     OPERATOR_INDEX_TAG=$(echo ${OPERATOR_INDEX_TAG_RAW} |cut -d'-' -f1)
+      #     skopeo inspect docker://${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}:${OPERATOR_INDEX_TAG} > /dev/null # error out if needed
+      #     OPERATOR_INDEX_DIGEST=$(skopeo inspect docker://${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}:${OPERATOR_INDEX_TAG} | jq -r ".Digest")
+      #     OPERATOR_INDEX_RESOLVED="${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}@${OPERATOR_INDEX_DIGEST}"
+      #     OPERATOR_INDEX="${OPP_MIRROR_INDEX_REGISTRY}/${OPP_MIRROR_INDEX_ORGANIZATION}/${OPP_MIRROR_INDEX_NAME}:${OPERATOR_INDEX_TAG}"
+      #     echo $OPERATOR_INDEX_RESOLVED
+      #     echo $OPERATOR_INDEX
+      #     echo "::set-output name=operator_index_resolved::${OPERATOR_INDEX_RESOLVED}"
+      #     echo "::set-output name=operator_index::${OPERATOR_INDEX}"
+      # - name: Initialize sign process
+      #   uses: operator-framework/community-operators@webhook
+      #   continue-on-error: true
+      #   env:
+      #     INDEX_SHA: "${{ steps.openshift-vars.outputs.index_sha }}"
+      #     webhook_type: 'json-extended'
+      #     webhook_url: 'https://api.enterprise.redhat.com/hydra/umb-bridge/v1/publish'
+      #     webhook_secret: ${{ secrets.SIGNATURE_WEBHOOK_SECRET }}
+      #     data: "{\"index_image\": \"${{ steps.openshift-vars.outputs.operator_index }}\", \"index_image_resolved\": \"${{ steps.openshift-vars.outputs.operator_index_resolved }}\"}"
+ 
+#   push-to-quay-ocp:
+#     name: "Push to quay / ocp"
+# 
+#     needs: pr-check
+#     if: needs.pr-check.outputs.opp_release_ready == '1' && needs.pr-check.outputs.opp_name != '' && needs.pr-check.outputs.opp_version != ''
+#     runs-on: ubuntu-latest
+#     env:
+#       DELETE_APPREG: "${{ needs.pr-check.outputs.opp_release_delete_appreg }}"
+#       OPP_VERSION: "${{ needs.pr-check.outputs.opp_version }}"
+#     steps:
+#       - name: Push to quay
+#         run: |
+#           echo "push_to_quay operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH"
+#           bash <(curl -sL $OPP_SCRIPT_URL) push_to_quay operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }} $OPP_THIS_REPO $OPP_THIS_BRANCH || true
+
+# #   release-sha-ocp:
+#     name: "Index production / ocp"
+#     needs: [ pr-check, release-ocp ]
+# 
+#     if: needs.pr-check.outputs.opp_release_ready == '1' && ( github.event.inputs.mirror_index_to_final_location == '' || github.event.inputs.mirror_index_to_final_location != '0')
+#     runs-on: ubuntu-latest
+#     strategy:
+#       matrix:
+# # #         index-tag: ['v4.6-db', 'v4.7-db', 'v4.8-db', 'v4.9-db', 'v4.10-db', 'v4.11']
+# # # 
+#       fail-fast: false
+#     steps:
+      # - name: Download operator_info
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     name: operator_info
+      #     path: /tmp/operator-test/
+      # - name: Download converted operators
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     name: operators_converted
+      #     path: /tmp/operator-test/operators
+
+      # - name: Release final index
+      #   env:
+      #     OPERATOR_INDEX_TAG: ${{ matrix.index-tag }}
+      #     IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
+      #     IIB_OUTPUT_REGISTRY_TOKEN: ${{ secrets.IIB_OUTPUT_REGISTRY_TOKEN }}
+      #   run: |
+      #     FAKE_RC=false
+      #     FAKE_TYPE=$(echo $OPERATOR_INDEX_TAG | cut -d '-' -f 2)
+      #     [[ $FAKE_TYPE == *rc* ]] && FAKE_RC=true || true
+
+      #     echo "openshift: $OPERATOR_INDEX_TAG"
+      #     bash <(curl -sL $OPP_SCRIPT_ISS_URL) openshift $OPERATOR_INDEX_TAG || $FAKE_RC
+# 
