Upgrade CI (23 Jan 2022 07:52:37)

diff --git a/.github/workflows/operator_test.yaml b/.github/workflows/operator_test.yaml
--- a/.github/workflows/operator_test.yaml
+++ b/.github/workflows/operator_test.yaml
@@ -89,14 +89,17 @@ jobs:
         run: |
           echo "::set-output name=opp_check_err_cluster_version_autolabel::0"
           [ -f /tmp/operator-test/op_failed_k8s_bundles.yaml ] && echo "::set-output name=opp_check_err_k8s_bundles::1" || true
+          [ -f /tmp/operator-test/op_failed_k8s_bundles.yaml ] && echo "::set-output name=opp_check_err_k8s_bundles_value::$(cat /tmp/operator-test/op_failed_k8s_bundles.yaml)" || true
       - name: Operator info (comment)
         id: op-info-comment
         if: always() && steps.op-info-result.outputs.opp_check_err_k8s_bundles == '1'
+        env:
+          K8S_BUNDLES_ERROR: ${{ steps.op-info-result.outputs.opp_check_err_k8s_bundles }}
         uses: mshick/add-pr-comment@v1
         with:
           message: |
             ## Missing k8s max version for some
-
+            $K8S_BUNDLES_ERROR
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
 
