Upgrade CI (21 Oct 2022 10:51:05)

diff --git a/.github/workflows/operator_test.yaml b/.github/workflows/operator_test.yaml
--- a/.github/workflows/operator_test.yaml
+++ b/.github/workflows/operator_test.yaml
@@ -25,15 +25,15 @@ env:
   OPP_RELEASE_INDEX_REGISTRY: "quay.io"
   OPP_RELEASE_INDEX_ORGANIZATION: "community-operators-pipeline"
   OPP_RELEASE_INDEX_NAME: "catalog_tmp"
-  OPP_MIRROR_INDEX_MULTIARCH_BASE: "registry.redhat.io/openshift4/ose-operator-registry"
-  OPP_MULTIARCH_SUPPORTED_VERSIONS: "v4.5 v4.6 v4.7 v4.8 v4.9 v4.10 v4.11 v4.12"
+  OPP_MIRROR_INDEX_MULTIARCH_BASE: "quay.io/operator-framework/opm"
+  OPP_MULTIARCH_SUPPORTED_VERSIONS: "latest"
   OPP_MIRROR_INDEX_MULTIARCH_POSTFIX: "s"
   IIB_INPUT_REGISTRY_USER: "mavala"
   OPP_PROD: 0
   OPP_DRY_RUN: 0
-  KIND_VERSION: "v0.16.0"
+  KIND_VERSION: "v0.14.0"
   KIND_KUBE_VERSION_LATEST: "v1.21.1"
-  OPP_PRODUCTION_TYPE: "ocp"
+  OPP_PRODUCTION_TYPE: "k8s"
   OPP_REVIEWERS_ENABLED: 0
   OPP_FORCE_DEPLOY_ON_K8S_OPENSHIFT_VERSION: 4.8
 #  ARTEFACT_PATH: "/tmp/operator-test" #hardcoded for now
@@ -114,8 +114,6 @@ jobs:
           # OPP_ANSIBLE_PULL_BRANCH="upstream-community-dev"
           [ "$OPP_AUTO_LABEL" = '1' ] && ANSIBLE_ARGS="-e automatic_cluster_version_label=true" || ANSIBLE_ARGS="-e automatic_cluster_version_label=false"
 
-          ANSIBLE_ARGS="$ANSIBLE_ARGS -e stream_kind=openshift_upstream"
-          echo $ANSIBLE_ARGS
 
           ansible-pull -U $OPP_ANSIBLE_PULL_REPO -C $OPP_ANSIBLE_PULL_BRANCH -i localhost, -e run_upstream=true -e run_prepare_catalog_repo_upstream=false -e run_remove_catalog_repo=false upstream/local.yml --tags reset_tools,operator_info -e operator_dir=$PWD/operators/operators/${{ steps.op-traffic-light.outputs.opp_name }} -e cluster_type=$OPP_PRODUCTION_TYPE -e strict_cluster_version_labels=true -e strict_k8s_bundles=true -e production_registry_namespace=$OPP_RELEASE_BUNDLE_REGISTRY/$OPP_RELEASE_BUNDLE_ORGANIZATION $ANSIBLE_ARGS
 
@@ -123,25 +121,22 @@ jobs:
         id: op-info-result
         if: always() && (steps.op-traffic-light.outputs.opp_op_delete == '0' || steps.op-traffic-light.outputs.opp_is_new_operatror == '1' || steps.op-traffic-light.outputs.opp_recreate == '1' ) && (steps.op-traffic-light.outputs.opp_ci_yaml_only == '0')
         run: |
-          echo "::set-output name=opp_check_err_cluster_version_autolabel::0"
-          [ -f /tmp/operator-test/op_auto_labels.yaml ] && echo "::set-output name=opp_check_err_cluster_version_autolabel::1" || true
+          echo "::set-output name=opp_check_err_k8s_bundles::0"
+          echo "::set-output name=opp_check_err_k8s_bundles_value::"
+          [ -f /tmp/operator-test/op_failed_k8s_bundles.yaml ] && echo "::set-output name=opp_check_err_k8s_bundles::1" || true
+          [ -f /tmp/operator-test/op_failed_k8s_bundles.yaml ] && echo "::set-output name=opp_check_err_k8s_bundles_value::$(cat /tmp/operator-test/op_failed_k8s_bundles.yaml | yq -r '.operators | @csv' | tr -d '"')" || true
       - name: Operator info (comment)
         id: op-info-comment
-        if: always() && steps.op-info-result.outputs.opp_check_err_cluster_version_autolabel == '1' && (steps.op-traffic-light.outputs.opp_op_delete == '0' || steps.op-traffic-light.outputs.opp_is_new_operatror == '1' )
+        if: always() && steps.op-info-result.outputs.opp_check_err_k8s_bundles == '1' && (steps.op-traffic-light.outputs.opp_op_delete == '0' || steps.op-traffic-light.outputs.opp_is_new_operatror == '1' || steps.op-traffic-light.outputs.opp_recreate == '1' ) && (steps.op-traffic-light.outputs.opp_ci_yaml_only == '0')
         uses: mshick/add-pr-comment@v1
         with:
           message: |
-            ## Automatic Cluster Version Label (OCP) - packagemanifest only
-
-            Starting OCP v4.9 (based on k8s 1.22) some old API were deprecated([Deprecated API Migration Guide from v1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22), [OKD/OpenShift Catalogs criteria and options](./packaging-required-criteria-ocp.md)). User can set `com.redhat.openshift.versions: <versions>`in its bundle `annotations.yaml` file to limit specific operator version to be visible on certain cluster.
-            Users can set label only when the operator is in bundle format. For packagemanifest format it is not possible to set this lablel, but community-operators pipeline can automatically set such label to the bundle. User have to allow it by putting packagemanifestClusterVersionLabel: auto in ci.yaml file
-
-            ```
-            $ cat <path-to-operator>/ci.yaml
-            packagemanifestClusterVersionLabel: auto
-            ```
-            More info [here](https://redhat-openshift-ecosystem.github.io/community-operators-pipeline/operator-ci-yaml/#automatic-cluster-version-label-ocp-packagemanifest-only).
-
+            Dear @${{ github.event.pull_request.user.login }},
+            There are some operators version that are using **deprecated api** and kubernetes max versions (`operatorhub.io/ui-metadata-max-k8s-version`) is **NOT** set correctly under annotation field in CSV file.
+            
+            Affected versions : `${{ steps.op-info-result.outputs.opp_check_err_k8s_bundles_value }}`
+            
+            More info in 'Kubernetes max version in CSV' section [here](https://redhat-openshift-ecosystem.github.io/community-operators-pipeline/operator-ci-yaml/#kubernetes-max-version-in-csv).
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
           allow-repeats: true
@@ -301,14 +296,14 @@ jobs:
           allow-repeats: true
 
 
-  test-lemon-openshift:
+  test-lemon:
     name: "lemon / Deploy from scratch"
     needs: pr-check
     if: needs.pr-check.outputs.opp_test_ready == '1' && (needs.pr-check.outputs.opp_op_delete == '0' || needs.pr-check.outputs.opp_is_new_operatror == '1' || needs.pr-check.outputs.opp_recreate == '1')  && needs.pr-check.outputs.opp_ci_yaml_only == '0'
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        index-tag: ['v4.6-db', 'v4.7-db', 'v4.8-db', 'v4.9-db', 'v4.10-db', 'v4.11', 'v4.12-rc']
+        index-tag: ['latest-db']
 
       fail-fast: false
     steps:
@@ -316,21 +311,6 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-      - name: Download operator_info
-        uses: actions/download-artifact@v2
-        with:
-          name: operator_info
-          path: /tmp/operator-test/
-      - name: Download converted operators
-        uses: actions/download-artifact@v2
-        with:
-          name: operators_converted
-          path: /tmp/operator-test/operators
-      - name: Debug artefacts
-        shell: bash
-        run: |
-          ls /tmp/operator-test/operators
-          head /tmp/operator-test/op_info.yaml
       - name: Operator test
         env:
           OPP_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
@@ -342,14 +322,14 @@ jobs:
 
 
 
-  test-orange-openshift:
-    name: "orange / Deploy o7t"
+  test-orange-latest:
+    name: "orange / Deploy k8s"
     needs: pr-check
-    if: needs.pr-check.outputs.opp_test_ready == '1' && (needs.pr-check.outputs.opp_op_delete == '0' || needs.pr-check.outputs.opp_is_new_operatror == '1' || needs.pr-check.outputs.opp_recreate == '1')  && needs.pr-check.outputs.opp_ci_yaml_only == '0'
+    if: needs.pr-check.outputs.opp_test_ready == '1' && (needs.pr-check.outputs.opp_op_delete == '0' || needs.pr-check.outputs.opp_is_new_operatror == '1' || needs.pr-check.outputs.opp_recreate == '1' )  && needs.pr-check.outputs.opp_ci_yaml_only == '0'
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        index-tag: ['v4.6-db', 'v4.7-db', 'v4.8-db', 'v4.9-db', 'v4.10-db', 'v4.11', 'v4.12-rc']
+        index-tag: ['latest-db']
 
       fail-fast: false
     steps:
@@ -357,29 +337,14 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-      - name: Download operator_info
-        uses: actions/download-artifact@v2
-        with:
-          name: operator_info
-          path: /tmp/operator-test/
-      - name: Download converted operators
-        uses: actions/download-artifact@v2
-        with:
-          name: operators_converted
-          path: /tmp/operator-test/operators
-      - name: Debug artefacts
-        shell: bash
-        run: |
-          ls /tmp/operator-test/operators
-          head /tmp/operator-test/op_info.yaml
       - name: Operator test
         env:
           OPP_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
           OPP_AUTO_PACKAGEMANIFEST_CLUSTER_VERSION_LABEL: "${{ needs.pr-check.outputs.opp_auto_packagemanifest_cluster_version_label }}"
-          OPERATOR_INDEX_TAG: ${{ matrix.index-tag }}
           OPP_MIRROR_INDEX_ENABLED: 1
           OPP_IIB_INSTALL: 1
           IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
+          OPERATOR_INDEX_TAG: ${{ matrix.index-tag }}
           OPP_INSTALLATION_SKIP: "${{ needs.pr-check.outputs.opp_installation_skipped }}"
         run: |
           echo "orange_${OPERATOR_INDEX_TAG} operators/${{ needs.pr-check.outputs.opp_name }}/${{ needs.pr-check.outputs.opp_version }}"
@@ -388,8 +353,8 @@ jobs:
 
   test-summary:
     name: "Summary"
-
-    needs: [ pr-check, test-kiwi, test-lemon-openshift, test-orange-openshift ]
+    
+    needs: [ pr-check, test-kiwi, test-lemon, test-orange-latest]
 
     if: always()
     runs-on: ubuntu-latest
